server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name 47.243.79.140;

	root /var/www/hot-acme;

	location ^~ /.well-known/acme-challenge/ {
		try_files $uri =404;
	}

	location / {
		return 404;
	}
}
