using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

// 隔离框架与HybridCLR生成程序集。项目仍可保留同名AOTGenericReferences生成类，
// 但Frame_Base、Frame_Game和编辑器工具不再需要直接引用AutoGenerated程序集。
public static class HybridCLRReferenceUtility
{
	private const string TYPE_NAME = "AOTGenericReferences";
	private const string MEMBER_NAME = "PatchedAOTAssemblyList";
	private static string[] mPatchedAOTAssemblyList;

	public static IReadOnlyList<string> getPatchedAOTAssemblyList()
	{
		return mPatchedAOTAssemblyList ??= load();
	}

	private static string[] load()
	{
		foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
		{
			Type type = assembly.GetType(TYPE_NAME, false);
			if (type == null) continue;
			object value = read(type);
			if (value == null) return Array.Empty<string>();
			if (value is not IEnumerable list)
			{
				throw new InvalidOperationException(TYPE_NAME + "." + MEMBER_NAME + "必须是字符串集合");
			}

			List<string> result = new();
			HashSet<string> unique = new(StringComparer.Ordinal);
			foreach (object item in list)
			{
				if (item is not string name || string.IsNullOrWhiteSpace(name))
				{
					throw new InvalidOperationException(TYPE_NAME + "." + MEMBER_NAME + "包含非法程序集名");
				}
				if (!unique.Add(name))
				{
					throw new InvalidOperationException(TYPE_NAME + "." + MEMBER_NAME + "包含重复程序集:" + name);
				}
				result.Add(name);
			}
			return result.ToArray();
		}
		return Array.Empty<string>();
	}

	private static object read(Type type)
	{
		const BindingFlags FLAGS = BindingFlags.Public | BindingFlags.Static;
		FieldInfo field = type.GetField(MEMBER_NAME, FLAGS);
		if (field != null) return field.GetValue(null);
		PropertyInfo property = type.GetProperty(MEMBER_NAME, FLAGS);
		return property?.GetValue(null);
	}
}
